// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probeAllocInfo struct {
	_           structs.HostLayout
	Size        uint64
	TimestampNs uint64
	StackId     int32
	_           [4]byte
}

type probeCombinedAllocInfo struct {
	_    structs.HostLayout
	Info struct {
		_ structs.HostLayout
		_ [8]byte
	}
}

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	AlignedAllocEnter         *ebpf.ProgramSpec `ebpf:"aligned_alloc_enter"`
	AlignedAllocExit          *ebpf.ProgramSpec `ebpf:"aligned_alloc_exit"`
	CallocEnter               *ebpf.ProgramSpec `ebpf:"calloc_enter"`
	CallocExit                *ebpf.ProgramSpec `ebpf:"calloc_exit"`
	FreeEnter                 *ebpf.ProgramSpec `ebpf:"free_enter"`
	MallocEnter               *ebpf.ProgramSpec `ebpf:"malloc_enter"`
	MallocExit                *ebpf.ProgramSpec `ebpf:"malloc_exit"`
	MemalignEnter             *ebpf.ProgramSpec `ebpf:"memalign_enter"`
	MemalignExit              *ebpf.ProgramSpec `ebpf:"memalign_exit"`
	MemleakKfree              *ebpf.ProgramSpec `ebpf:"memleak__kfree"`
	MemleakKmalloc            *ebpf.ProgramSpec `ebpf:"memleak__kmalloc"`
	MemleakKmallocNode        *ebpf.ProgramSpec `ebpf:"memleak__kmalloc_node"`
	MemleakKmemCacheAlloc     *ebpf.ProgramSpec `ebpf:"memleak__kmem_cache_alloc"`
	MemleakKmemCacheAllocNode *ebpf.ProgramSpec `ebpf:"memleak__kmem_cache_alloc_node"`
	MemleakKmemCacheFree      *ebpf.ProgramSpec `ebpf:"memleak__kmem_cache_free"`
	MemleakMmPageAlloc        *ebpf.ProgramSpec `ebpf:"memleak__mm_page_alloc"`
	MemleakMmPageFree         *ebpf.ProgramSpec `ebpf:"memleak__mm_page_free"`
	MemleakPercpuAllocPercpu  *ebpf.ProgramSpec `ebpf:"memleak__percpu_alloc_percpu"`
	MemleakPercpuFreePercpu   *ebpf.ProgramSpec `ebpf:"memleak__percpu_free_percpu"`
	MmapEnter                 *ebpf.ProgramSpec `ebpf:"mmap_enter"`
	MmapExit                  *ebpf.ProgramSpec `ebpf:"mmap_exit"`
	MunmapEnter               *ebpf.ProgramSpec `ebpf:"munmap_enter"`
	PosixMemalignEnter        *ebpf.ProgramSpec `ebpf:"posix_memalign_enter"`
	PosixMemalignExit         *ebpf.ProgramSpec `ebpf:"posix_memalign_exit"`
	PvallocEnter              *ebpf.ProgramSpec `ebpf:"pvalloc_enter"`
	PvallocExit               *ebpf.ProgramSpec `ebpf:"pvalloc_exit"`
	ReallocEnter              *ebpf.ProgramSpec `ebpf:"realloc_enter"`
	ReallocExit               *ebpf.ProgramSpec `ebpf:"realloc_exit"`
	VallocEnter               *ebpf.ProgramSpec `ebpf:"valloc_enter"`
	VallocExit                *ebpf.ProgramSpec `ebpf:"valloc_exit"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	Allocs         *ebpf.MapSpec `ebpf:"allocs"`
	CombinedAllocs *ebpf.MapSpec `ebpf:"combined_allocs"`
	Memptrs        *ebpf.MapSpec `ebpf:"memptrs"`
	Sizes          *ebpf.MapSpec `ebpf:"sizes"`
	StackTraces    *ebpf.MapSpec `ebpf:"stack_traces"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
	MaxSize       *ebpf.VariableSpec `ebpf:"max_size"`
	MinSize       *ebpf.VariableSpec `ebpf:"min_size"`
	PageSize      *ebpf.VariableSpec `ebpf:"page_size"`
	SampleRate    *ebpf.VariableSpec `ebpf:"sample_rate"`
	StackFlags    *ebpf.VariableSpec `ebpf:"stack_flags"`
	TargetPid     *ebpf.VariableSpec `ebpf:"target_pid"`
	TraceAll      *ebpf.VariableSpec `ebpf:"trace_all"`
	WaMissingFree *ebpf.VariableSpec `ebpf:"wa_missing_free"`
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	Allocs         *ebpf.Map `ebpf:"allocs"`
	CombinedAllocs *ebpf.Map `ebpf:"combined_allocs"`
	Memptrs        *ebpf.Map `ebpf:"memptrs"`
	Sizes          *ebpf.Map `ebpf:"sizes"`
	StackTraces    *ebpf.Map `ebpf:"stack_traces"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.Allocs,
		m.CombinedAllocs,
		m.Memptrs,
		m.Sizes,
		m.StackTraces,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
	MaxSize       *ebpf.Variable `ebpf:"max_size"`
	MinSize       *ebpf.Variable `ebpf:"min_size"`
	PageSize      *ebpf.Variable `ebpf:"page_size"`
	SampleRate    *ebpf.Variable `ebpf:"sample_rate"`
	StackFlags    *ebpf.Variable `ebpf:"stack_flags"`
	TargetPid     *ebpf.Variable `ebpf:"target_pid"`
	TraceAll      *ebpf.Variable `ebpf:"trace_all"`
	WaMissingFree *ebpf.Variable `ebpf:"wa_missing_free"`
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	AlignedAllocEnter         *ebpf.Program `ebpf:"aligned_alloc_enter"`
	AlignedAllocExit          *ebpf.Program `ebpf:"aligned_alloc_exit"`
	CallocEnter               *ebpf.Program `ebpf:"calloc_enter"`
	CallocExit                *ebpf.Program `ebpf:"calloc_exit"`
	FreeEnter                 *ebpf.Program `ebpf:"free_enter"`
	MallocEnter               *ebpf.Program `ebpf:"malloc_enter"`
	MallocExit                *ebpf.Program `ebpf:"malloc_exit"`
	MemalignEnter             *ebpf.Program `ebpf:"memalign_enter"`
	MemalignExit              *ebpf.Program `ebpf:"memalign_exit"`
	MemleakKfree              *ebpf.Program `ebpf:"memleak__kfree"`
	MemleakKmalloc            *ebpf.Program `ebpf:"memleak__kmalloc"`
	MemleakKmallocNode        *ebpf.Program `ebpf:"memleak__kmalloc_node"`
	MemleakKmemCacheAlloc     *ebpf.Program `ebpf:"memleak__kmem_cache_alloc"`
	MemleakKmemCacheAllocNode *ebpf.Program `ebpf:"memleak__kmem_cache_alloc_node"`
	MemleakKmemCacheFree      *ebpf.Program `ebpf:"memleak__kmem_cache_free"`
	MemleakMmPageAlloc        *ebpf.Program `ebpf:"memleak__mm_page_alloc"`
	MemleakMmPageFree         *ebpf.Program `ebpf:"memleak__mm_page_free"`
	MemleakPercpuAllocPercpu  *ebpf.Program `ebpf:"memleak__percpu_alloc_percpu"`
	MemleakPercpuFreePercpu   *ebpf.Program `ebpf:"memleak__percpu_free_percpu"`
	MmapEnter                 *ebpf.Program `ebpf:"mmap_enter"`
	MmapExit                  *ebpf.Program `ebpf:"mmap_exit"`
	MunmapEnter               *ebpf.Program `ebpf:"munmap_enter"`
	PosixMemalignEnter        *ebpf.Program `ebpf:"posix_memalign_enter"`
	PosixMemalignExit         *ebpf.Program `ebpf:"posix_memalign_exit"`
	PvallocEnter              *ebpf.Program `ebpf:"pvalloc_enter"`
	PvallocExit               *ebpf.Program `ebpf:"pvalloc_exit"`
	ReallocEnter              *ebpf.Program `ebpf:"realloc_enter"`
	ReallocExit               *ebpf.Program `ebpf:"realloc_exit"`
	VallocEnter               *ebpf.Program `ebpf:"valloc_enter"`
	VallocExit                *ebpf.Program `ebpf:"valloc_exit"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.AlignedAllocEnter,
		p.AlignedAllocExit,
		p.CallocEnter,
		p.CallocExit,
		p.FreeEnter,
		p.MallocEnter,
		p.MallocExit,
		p.MemalignEnter,
		p.MemalignExit,
		p.MemleakKfree,
		p.MemleakKmalloc,
		p.MemleakKmallocNode,
		p.MemleakKmemCacheAlloc,
		p.MemleakKmemCacheAllocNode,
		p.MemleakKmemCacheFree,
		p.MemleakMmPageAlloc,
		p.MemleakMmPageFree,
		p.MemleakPercpuAllocPercpu,
		p.MemleakPercpuFreePercpu,
		p.MmapEnter,
		p.MmapExit,
		p.MunmapEnter,
		p.PosixMemalignEnter,
		p.PosixMemalignExit,
		p.PvallocEnter,
		p.PvallocExit,
		p.ReallocEnter,
		p.ReallocExit,
		p.VallocEnter,
		p.VallocExit,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfel.o
var _ProbeBytes []byte
